version: "3.7"
services:
  postgres:
    image: postgres:16.1
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./transactiondb.sql:/docker-entrypoint-initdb.d/migration.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:5.5.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-enterprise-kafka:5.5.3
    depends_on: 
      - zookeeper
    ports:
      - "9093:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  anti-fraud-service:
    build: ./anti-fraud-service
    ports:
      - "3001:3000"
    environment:
      KAFKA_BROKER: kafka:9093
      KAFKA_CLIENT_ID: antiFraudService
      KAFKA_GROUP_ID: antiFraudGroup
    depends_on:
      - kafka

  transaction-service:
    build: ./transaction-service
    depends_on:
      - postgres
      - kafka
    ports:
      - "3002:3000"
    environment:
      KAFKA_BROKER: kafka:9093
      KAFKA_CLIENT_ID: transaction_service
      KAFKA_GROUP_ID: transaction_group
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: transactiondb
